name: MyGameHub Streamlit App

on:
  push:
    branches: ["dev", "master"]
  pull_request:
    branches: ["dev", "master"]

permissions:
  contents: read

jobs:
  app-tests:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: "sk-svcacct-XilnF3KG3SaQiqbSj3MlT3BlbkFJxgpB6yDM9CrjxfxhlpMz"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --ignore=pages/tests/test_mario.py
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: Home.py