name: MyGameHub Streamlit App

on:
  push:
    branches: ["dev", "master"]
  pull_request:
    branches: ["dev", "master"]

permissions:
  contents: read

jobs:
  app-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"